package com.sample
import com.sample.DroolsTest.*;

//1
rule "The End"
salience 1
	when
		a1: Attribute(my_id == "accept", parameters.contains("Tak")) &&
		a: Attribute(my_id != "accept")
	then
		retract(a);
end
//2
rule "Delete Accept"
salience -2
	when
		a1: Attribute(my_id == "accept", parameters.contains("Tak")) 
	then
		retract(a1);
end
//3
rule "No result"
salience -1
	when
		a: Attribute(my_id == "accept", !parameters.contains("Tak"))
	then
		Question.displayResult("Brak potraw spełniających Twoje wymagania");
end
//4
rule "Init"
salience 1
	when 
	then
		System.out.println("Init");
		insert( new Attribute("fastFood") ); 
		insert( new Attribute("diet") );
		insert( new Attribute("meat") );
		insert( new Attribute("taste") );
		insert( new Attribute("accept") );
		insert( new Attribute("prefMeat") );
		insert( new Attribute("mushroom") );
		insert( new Attribute("vegetables") );
		insert( new Attribute("isSpinach") );
		insert( new Attribute("cheese") );
		insert( new Attribute("sthToDrink") );
		insert( new Attribute("flour") );
		insert( new Attribute("fruit") );
		insert( new Attribute("fish") );
		insert( new Attribute("likeExtras") );
		insert( new Attribute("potatoes") );
	end
//5
rule "Choose diet"
salience 1
	when 
		a: Attribute( my_id == "diet", parameters.isEmpty())
	then
		a.getParams(Question.oneFromFewOption(new String [] {"mięso", "ryby", "potrawa wegetariańska"}, "Na co masz dzisiaj ochotę?"));
		update(a);
end
//6
rule "Fast Food?"
 	when 
		a1: Attribute( my_id == "fastFood", parameters.isEmpty()) &&
		(a2: Attribute( my_id == "diet", parameters.contains("mięso")) ||
		a3: Attribute( my_id == "diet", parameters.contains("potrawa wegetariańska") ))
	then
		a1.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Może preferujesz fast food?"));
		update(a1);
end

//7
rule "Taste"
	when 
		a1: Attribute( my_id == "taste", parameters.isEmpty()) &&
		a2: Attribute( my_id == "fastFood", parameters.contains("Nie")) &&
		a3: Attribute( my_id == "diet", parameters.contains("potrawa wegetariańska"))
	then
		a1.getParams(Question.oneFromFewOption(new String [] {"danie wytrawne", "danie na słodko"}, "Danie wytrawne czy słodkie?"));
		update(a1);
end

//8
rule "likeExtras"
no-loop
	when 
		a1: Attribute( my_id == "likeExtras", parameters.isEmpty()) &&
		a2: Attribute( my_id == "fastFood", parameters.contains("Nie")) &&
		(a3: Attribute( my_id == "diet", parameters.contains("mięso")) ||
		a4: Attribute( my_id == "taste", parameters.contains("danie wytrawne")))
	then
		a1.getParams(Question.fewOptions(new String [] {"ryż", "makaron", "ziemniaki"}, "Które z poniższych produktów żywnościowych przypadają Ci do gustu?"));
		update(a1);
		drools.getRule().setLockOnActive(true);
end

//9
rule "Preferred meat"
salience 1
no-loop
	when
		a1: Attribute( my_id == "diet", parameters.contains("mięso")) &&
		a2: Attribute( my_id == "prefMeat", parameters.isEmpty())
	then 
	    a2.getParams(Question.fewOptions(new String [] {"wołowina", "wieprzowina", "mięso drobiowe", "baranina"}, "Wybierz lubiane przez Ciebie gatunki mięsa"));
		update(a2);
		drools.getRule().setLockOnActive(true);
end	
//10
rule "Mushroom"
	when
		a1: Attribute( my_id == "mushroom", parameters.isEmpty()) &&
		(((a2: Attribute( my_id == "taste", parameters.contains("danie wytrawne")) && (a3: Attribute( my_id == "likeExtras", parameters.contains("makaron"))||
		a4: Attribute( my_id == "flour", parameters.contains("Tak")))) || 
		(a5: Attribute( my_id == "prefMeat", (parameters.contains("wołowina") || parameters.contains("wieprzowina"))) && Attribute( my_id == "fastFood", parameters.contains("Nie")))) || 		
		(a6: Attribute( my_id == "fastFood", parameters.contains("Tak")) && 
		 a7: Attribute( my_id == "cheese", parameters.contains("Tak")) && 
		 a8: Attribute( my_id == "diet", parameters.contains("potrawa wegetariańska"))))
	then
		a1.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Czy lubisz grzyby?"));
		update(a1);
end

//11
rule "Vegetables"
no-loop
	when
		a1: Attribute( my_id == "vegetables", parameters.isEmpty()) &&
		a2: Attribute( my_id == "taste", parameters.contains("danie wytrawne"))
	then 
		a1.getParams(Question.fewOptions(new String [] {"pomidor", "sałata", "kukurydza", "kapusta pekińska", "włoszczyzna", "ogórek", "szpinak", "kapusta biała"}, "Wybierz, które warzywa lubisz"));
		update(a1);
		drools.getRule().setLockOnActive(true);
end

//63
rule "VegetablesForFish"
no-loop
	when
		a1: Attribute( my_id == "vegetables", parameters.isEmpty()) &&
		a2: Attribute( my_id == "diet", parameters.contains("ryby"))
	then 
		a1.getParams(Question.fewOptions(new String [] {"pomidor", "sałata", "kukurydza", "kapusta pekińska", "włoszczyzna", "ogórek kiszony", "cebula"}, "Wybierz, które warzywa lubisz"));
		update(a1);
		drools.getRule().setLockOnActive(true);
end

//12
rule "VegetablesForMeat"
no-loop
	when
		a1: Attribute( my_id == "vegetables", parameters.isEmpty()) &&
		a2: Attribute( my_id == "diet", parameters.contains("mięso")) &&
		a3: Attribute( my_id == "fastFood", parameters.contains("Nie"))
	then 
		a1.getParams(Question.fewOptions(new String [] {"kapusta biała", "brokuły", "włoszczyzna", "szpinak"}, "Za którymi warzywami przepadasz?"));
		update(a1);
		drools.getRule().setLockOnActive(true);
end

//13
rule "Really spinach?"
salience 1
no-loop
	when 
		a1: Attribute( my_id == "isSpinach", parameters.isEmpty()) &&
		a2: Attribute( my_id == "vegetables", parameters.contains("szpinak"))
	then 
		a1.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Naprawdę lubisz szpinak? :P"));
		update(a1);
end		
//14
rule "Cheese"
	when
		a1: Attribute( my_id == "cheese", parameters.isEmpty()) &&
		a2: Attribute( my_id == "fastFood", parameters.contains("Tak")) &&
		(a3: Attribute( my_id == "prefMeat", parameters.contains("wołowina")) || 		
		a4:  Attribute( my_id == "diet", parameters.contains("potrawa wegetariańska")))
	then
		a1.getParams( Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Czy lubisz ser żółty?"));
		update(a1);
end	
//15
rule "Souce"
	when 
		a1: Attribute( my_id == "prefMeat", parameters.contains("baranina")) &&
		a2: Attribute( my_id == "fastFood", parameters.contains("Tak"))
		a3: Attribute( my_id == "sthToDrink", parameters.isEmpty())
	then
		a3.getParams( Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Czy masz pod ręką kilka litrów zimnych napojów? :P"));
		update(a3);
end
//16
rule "Flour"
	when 
		a1: Attribute( my_id == "flour", parameters.isEmpty()) &&
		a2: Attribute( my_id == "diet", parameters.contains("potrawa wegetariańska")) &&
		a3: Attribute( my_id == "fastFood", parameters.contains("Nie"))
	then
		a1.getParams( Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Czy lubisz dania mączne, takie jak naleśniki, pierogi itp.?"));
		update(a1);
end
//17
rule "Fruit"
no-loop
	when
		a1: Attribute( my_id == "fruit", parameters.isEmpty()) &&
		a2: Attribute( my_id == "taste", parameters.contains("danie na słodko")) 
	then
		a1.getParams(Question.fewOptions(new String [] {"truskawki", "jagody", "jabłka"}, "Które z poniższych owoców lubisz?"));
		update(a1);
		drools.getRule().setLockOnActive(true);
end
//18
rule "Fish"
no-loop
	when
		a1: Attribute( my_id == "fish", parameters.isEmpty()) &&
		a2: Attribute( my_id == "diet", parameters.contains("ryby")) 
	then
		a1.getParams(Question.fewOptions(new String [] {"panga", "tuńczyk", "śledzie", "dorsz", "morszczuk"}, "Na jakie ryby masz ochotę?"));
		update(a1);
		drools.getRule().setLockOnActive(true);
end
//19
rule "Potatoes"
	when
		a1: Attribute( my_id == "fish", (parameters.contains("panga") || parameters.contains("morszczuk")))  &&
		a2: Attribute( my_id == "potatoes", parameters.isEmpty()) 
	then
		a2.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Czy lubisz ziemniaki?"));
		update(a2);
end


/* Dania rybne */
//20
rule "Sałatka z tuńczykiem"
no-loop
	when
		a1: Attribute( my_id == "fish", parameters.contains("tuńczyk")) &&
		a2: Attribute( my_id == "vegetables", 
					   ((parameters.contains("pomidor") || parameters.contains("kukurydza")) && 
					   	(parameters.contains("kapusta pekińska") || parameters.contains("sałata"))))  &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Sałatka z tuńczykiem (tuńczyk + pomidor i/lub kukurydza + sałata lub kapusta pekińska). Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//21
rule "Ryba po grecku"
no-loop
	when
		a1: Attribute( my_id == "fish", (parameters.contains("panga") || parameters.contains("morszczuk") || parameters.contains("dorsz"))) &&
		a2: Attribute( my_id == "vegetables", parameters.contains("włoszczyzna"))  &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Ryba po grecku . Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//22
rule "Paluszki rybne"
no-loop
	when
		a1: Attribute( my_id == "fish", (parameters.contains("morszczuk") || parameters.contains("dorsz"))) &&
		a2: Attribute( my_id == "accept")
	then
		a2.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Paluszki rybne. Czy akceptujesz ten wybór?"));
		update(a2);
		drools.getRule().setLockOnActive(true);
end
//23
rule "Ryba + ziemniaki"
no-loop
	when
		a1: Attribute( my_id == "fish", (parameters.contains("panga") || parameters.contains("morszczuk"))) &&
		a2: Attribute( my_id == "potatoes", parameters.contains("Tak"))  &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Ryba (panga lub morszczuk) + ziemniaki . Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end	
//24
rule "Ryba w panierce"
no-loop
	when
		a1: Attribute( my_id == "fish", (parameters.contains("panga") || parameters.contains("morszczuk"))) &&
		a2: Attribute( my_id == "potatoes", parameters.contains("Nie"))  &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Ryba (panga lub morszczuk) w panierce. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//25
rule "Śledzie w śmietanie "
no-loop
	when
		a1: Attribute( my_id == "fish", parameters.contains("śledzie")) &&
		a2: Attribute( my_id == "accept")
	then
		a2.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Śledzie w śmietanie. Czy akceptujesz ten wybór?"));
		update(a2);
		drools.getRule().setLockOnActive(true);
end
//26
rule "Sałatka śledziowa "
no-loop
	when
		a1: Attribute( my_id == "fish", parameters.contains("śledzie")) &&
		a2: Attribute( my_id == "vegetables", (parameters.contains("cebula") || parameters.contains("ogórek kiszony") || parameters.contains("włoszczyzna"))) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Sałatka śledziowa. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
/* Dania wegetariańskie */	
/** Dania słodkie **/
//27
rule "Pierogi z truskawkami"
no-loop
	when
		a1: Attribute( my_id == "flour", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "fruit", parameters.contains("truskawki")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Pierogi z truskawkami. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//28
rule "Pierogi z jagodami"
no-loop
	when
		a1: Attribute( my_id == "flour", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "fruit", parameters.contains("jagody")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Pierogi z jagodami. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//29
rule "Placki z jabłkami"
no-loop
	when
		a1: Attribute( my_id == "flour", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "fruit", parameters.contains("jabłka")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Placki z jabłkami. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//30
rule "Omlet z jagodami"
no-loop
	when
		a1: Attribute( my_id == "fruit", parameters.contains("jagody")) &&
		a2: Attribute( my_id == "accept")
	then
		a2.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Omlet z jagodami. Czy akceptujesz ten wybór?"));
		update(a2);
		drools.getRule().setLockOnActive(true);
end
//31
rule "Naleśniki z dżemem truskawkowym"
no-loop
	when
		a1: Attribute( my_id == "flour", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "fruit", parameters.contains("truskawki")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Naleśniki z dżemem truskawkowym. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end 
/** Dania wytrawne **/
//32
rule "Pierogi z kapustą i grzybami"
no-loop
	when
		a1: Attribute( my_id == "flour", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "vegetables", parameters.contains("kapusta biała")) &&
		a3: Attribute( my_id == "mushroom", parameters.contains("Tak")) &&
		a4: Attribute( my_id == "accept")
	then
		a4.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Pierogi z kapustą i grzybami. Czy akceptujesz ten wybór?"));
		update(a4);
		drools.getRule().setLockOnActive(true);
end
//33
rule "Krokiety z farszem grzybowym"
no-loop
	when
		a1: Attribute( my_id == "flour", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "mushroom", parameters.contains("Tak")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Krokiety z farszem grzybowym. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//34
rule "Pierogi ze szpinakiem"
no-loop
	when
		a1: Attribute( my_id == "flour", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "isSpinach", parameters.contains("Tak")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Pierogi ze szpinakiem. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//35
rule "Placki ziemniaczane"
no-loop
	when
		a1: Attribute( my_id == "taste", parameters.contains("danie wytrawne")) &&
		a2: Attribute( my_id == "likeExtras", parameters.contains("ziemniaki")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Placki ziemniaczane. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//36
rule "Spaghetti Napoli"
no-loop
	when
		a1: Attribute( my_id == "likeExtras", parameters.contains("makaron")) &&
		a2: Attribute( my_id == "vegetables", parameters.contains("pomidor")) &&
		a3: Attribute( my_id == "taste", parameters.contains("danie wytrawne")) &&
		a4: Attribute( my_id == "accept")
	then
		a4.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Spaghetti Napoli. Czy akceptujesz ten wybór?"));
		update(a4);
		drools.getRule().setLockOnActive(true);
end
//37
rule "Sałatka ryżowa"
no-loop
	when
		a1: Attribute( my_id == "likeExtras", parameters.contains("ryż")) &&
		a2: Attribute( my_id == "vegetables", (parameters.contains("pomidor") && parameters.contains("kukurydza"))) &&
		a3: Attribute( my_id == "taste", parameters.contains("danie wytrawne")) &&
		a4: Attribute( my_id == "accept")
	then
		a4.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Sałatka ryżowa z pomidorem i kukurydzą. Czy akceptujesz ten wybór?"));
		update(a4);
		drools.getRule().setLockOnActive(true);
end
//38
rule "Sałatka makaronowa"
no-loop
	when
		a1: Attribute( my_id == "likeExtras", parameters.contains("makaron")) &&
		a2: Attribute( my_id == "vegetables", (parameters.contains("pomidor") && parameters.contains("kukurydza") && parameters.contains("ogórek"))) &&
		a3: Attribute( my_id == "taste", parameters.contains("danie wytrawne")) &&
		a4: Attribute( my_id == "accept")
	then
		a4.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Sałatka makaronowa z pomidorem, ogórkiem i kukurydzą. Czy akceptujesz ten wybór?"));
		update(a4);
		drools.getRule().setLockOnActive(true);
end
//39
rule "Sałatka warzywna"
no-loop
	when
		a1: Attribute( my_id == "likeExtras", parameters.contains("ziemniaki")) &&
		a2: Attribute( my_id == "vegetables", parameters.contains("włoszczyzna")) &&
		a3: Attribute( my_id == "taste", parameters.contains("danie wytrawne")) &&
		a4: Attribute( my_id == "accept")
	then
		a4.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Sałatka warzywna (ziemniaki + włoszczyzna).Czy akceptujesz ten wybór?"));
		update(a4);
		drools.getRule().setLockOnActive(true);
end

//40
rule "Surówka z kapusty pekińskiej"
no-loop
	when
		a1: Attribute( my_id == "vegetables", (parameters.contains("kapusta pekińska") && parameters.contains("pomidor") && parameters.contains("kukurydza"))) &&
		a2: Attribute( my_id == "taste", parameters.contains("danie wytrawne")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Surówka z kapustą pekińską, pomidorem i kukurydzą.Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);\		
end
//41
rule "Makaron ze szpinakiem"
no-loop
	when
		a1: Attribute( my_id == "likeExtras", parameters.contains("makaron")) &&
		a2: Attribute( my_id == "isSpinach",(parameters.contains("Tak") && !parameters.contains("Nie"))) &&
		a3: Attribute( my_id == "taste", parameters.contains("danie wytrawne")) &&
		a4: Attribute( my_id == "accept")
	then
		a4.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Makaron ze szpinakiem. Czy akceptujesz ten wybór?"));
		update(a4);
		drools.getRule().setLockOnActive(true);
end
//42
rule "Makaron w sosie grzybowym"
no-loop
	when
		a1: Attribute( my_id == "likeExtras", parameters.contains("makaron")) &&
		a2: Attribute( my_id == "mushroom",parameters.contains("Tak")) &&
		a3: Attribute( my_id == "taste", parameters.contains("danie wytrawne")) &&
		a4: Attribute( my_id == "accept")
	then
		a4.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Makaron w sosie grzybowym. Czy akceptujesz ten wybór?"));
		drools.getRule().setLockOnActive(true);
		update(a4);
end

/* Danie mięsne */
//43
rule "Bigos"
no-loop
	when
		a1: Attribute( my_id == "prefMeat", parameters.contains("wieprzowina")) &&
		a2: Attribute( my_id == "mushroom", parameters.contains("Tak")) &&
		a3: Attribute( my_id == "vegetables", parameters.contains("kapusta biała")) &&
		a4: Attribute( my_id == "accept")
	then
		a4.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Bigos. Czy akceptujesz ten wybór?"));
		update(a4);
		drools.getRule().setLockOnActive(true);
end
//44
rule "Kurczak ze szpinakiem"
no-loop
	when
		a1: Attribute( my_id == "prefMeat", parameters.contains("mięso drobiowe")) &&
		a2: Attribute( my_id == "isSpinach",parameters.contains("Tak")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Kurczak ze szpinakiem. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//45
rule "Filet z kurczaka z ziemniakami"
no-loop
	when
		a1: Attribute( my_id == "prefMeat", parameters.contains("mięso drobiowe")) &&
		a2: Attribute( my_id == "likeExtras", parameters.contains("ziemniaki")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Filet z kurczaka z ziemniakami. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//46
rule "Kotlet schabowy z ziemniakami"
no-loop
	when
		a1: Attribute( my_id == "prefMeat", parameters.contains("wieprzowina")) &&
		a2: Attribute( my_id == "likeExtras", parameters.contains("ziemniaki")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Kotlet schabowy z ziemniakami. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//47
rule "Spaghetti Bolognese"
no-loop
	when
		a1: Attribute( my_id == "likeExtras", parameters.contains("makaron")) &&
		a2: Attribute( my_id == "prefMeat", parameters.contains("wieprzowina")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Spaghetti bolognese. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//48
rule "Risotto z kurczakiem"
no-loop
	when
		a1: Attribute( my_id == "likeExtras", parameters.contains("ryż")) &&
		a2: Attribute( my_id == "prefMeat", parameters.contains("mięso drobiowe")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Risotto z kurczakiem. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//49
rule "Zapiekanka makaronowa z kurczakiem"
no-loop
	when
		a1: Attribute( my_id == "likeExtras", parameters.contains("makaron")) &&
		a2: Attribute( my_id == "prefMeat", (parameters.contains("mięso drobiowe") || parameters.contains("wieprzowina")  || parameters.contains("wołowina"))) &&
		a3: Attribute( my_id == "vegetables", parameters.contains("brokuły")) 
		a4: Attribute( my_id == "accept")
	then
		a4.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Zapiekanka makaronowa z mięsem mielonym i brokułami. Czy akceptujesz ten wybór?"));
		update(a4);
		drools.getRule().setLockOnActive(true);
end

//50
rule "Gulasz wołowy"
no-loop
	when
		a1: Attribute( my_id == "prefMeat", parameters.contains("wołowina")) &&
		a3: Attribute( my_id == "accept") &&
		a4: Attribute( my_id == "mushroom", parameters.contains("Tak"))
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Gulasz wołowy z pieczarkami. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end

//51
rule "Stek wołowy"
no-loop
	when
		a1: Attribute( my_id == "prefMeat", parameters.contains("wołowina")) &&
		a2: Attribute( my_id == "accept")
	then
		a2.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Stek wołowy. Czy akceptujesz ten wybór?"));
		update(a2);
		drools.getRule().setLockOnActive(true);
end

//52
rule "Duszona baranina z warzywami"
no-loop
	when
		a1: Attribute( my_id == "prefMeat", parameters.contains("baranina")) &&
		a2: Attribute( my_id == "vegetables", parameters.contains("włoszczyzna")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Duszona baranina z warzywami. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end

//53
rule "Pieczona baranina"
no-loop
	when
		a1: Attribute( my_id == "prefMeat", parameters.contains("baranina")) &&
		a2: Attribute( my_id == "likeExtras", parameters.contains("ziemniaki")) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Pieczona baranina z ziemniakami Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end

//54
rule "Gołąbki"
no-loop
	when
		a1: Attribute( my_id == "vegetables", parameters.contains("kapusta biała")) &&
		a2: Attribute( my_id == "prefMeat", parameters.contains("wieprzowina")) &&
		a3: Attribute( my_id == "likeExtras", parameters.contains("ryż")) &&
		a4: Attribute( my_id == "accept")
	then
		a4.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Gołąbki. Czy akceptujesz ten wybór?"));
		update(a4);
		drools.getRule().setLockOnActive(true);
end

/* Fast Food */
//55
rule "Zapiekanka z pieczarkami"
no-loop
	when
		a1: Attribute( my_id == "fastFood", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "mushroom", parameters.contains("Tak")) &&
		a3: Attribute( my_id == "accept")		
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Zapiekanka z pieczarkami. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//56
rule "Frytki"
no-loop
	when
		a1: Attribute( my_id == "fastFood", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "diet", parameters.contains("potrawa wegetariańska")) &&
		a3: Attribute( my_id == "accept")		
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Frytki. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);		
end
//57
rule "Hot dog"
no-loop
	when 
		a1: Attribute( my_id == "prefMeat", (parameters.contains("wieprzowina") || parameters.contains("mięso drobiowe"))) &&	
		a2: Attribute( my_id == "fastFood", parameters.contains("Tak")) &&
		a3: Attribute( my_id == "accept")		
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Hot dog. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//58		
rule "Hamburger"
no-loop
	when
		a1: Attribute( my_id == "fastFood", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "prefMeat", parameters.contains("wołowina")) &&		
		a3: Attribute( my_id == "accept")				
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Hamburger. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//59
rule "Cheeseburger"
no-loop
	when
		a1: Attribute( my_id == "fastFood", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "prefMeat", parameters.contains("wołowina")) &&		
		a3: Attribute( my_id == "accept") &&
		a4: Attribute( my_id == "cheese", parameters.contains("Tak"))		
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Cheeseburger. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end
//60
rule "Kebab1"
no-loop
	when 
		a1: Attribute( my_id == "sthToDrink", parameters.contains("Tak")) &&
		a2: Attribute( my_id == "accept")		
	then
		a2.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Kebab z sosem ostrym. Czy akceptujesz ten wybór?"));
		update(a2);
		drools.getRule().setLockOnActive(true);
end 	 
//61
rule "Kebab2"
no-loop
	when 
		a1: Attribute( my_id == "sthToDrink", parameters.contains("Nie")) && 
		a2: Attribute( my_id == "accept")
	then
		a2.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: Kebab z sosem łagodnym. Czy akceptujesz ten wybór?"));
		update(a2);
		drools.getRule().setLockOnActive(true);
end 	 	
//62
rule "Nuggetsy"
no-loop
	when
		a1: Attribute( my_id == "fastFood", parameters.contains("Tak") ) &&
		a2: Attribute( my_id == "prefMeat", parameters.contains("mięso drobiowe") ) &&
		a3: Attribute( my_id == "accept")
	then
		a3.getParams(Question.oneFromFewOption(new String [] {"Tak", "Nie"}, "Potrawa dla Ciebie to: nuggetsy. Czy akceptujesz ten wybór?"));
		update(a3);
		drools.getRule().setLockOnActive(true);
end


